# Use the official Node.js image
FROM node:18
WORKDIR /app
# Copy package
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire application source code
COPY . .

# Expose the port the service runs on
EXPOSE 5009

CMD ["npm", "start"]
